# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import node_conn_pb2 as node__conn__pb2


class LedManipulationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartLedPerformance = channel.unary_unary(
                '/LedManipulationService/StartLedPerformance',
                request_serializer=node__conn__pb2.TextMessage.SerializeToString,
                response_deserializer=node__conn__pb2.TextMessage.FromString,
                )


class LedManipulationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartLedPerformance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LedManipulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartLedPerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLedPerformance,
                    request_deserializer=node__conn__pb2.TextMessage.FromString,
                    response_serializer=node__conn__pb2.TextMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LedManipulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LedManipulationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartLedPerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LedManipulationService/StartLedPerformance',
            node__conn__pb2.TextMessage.SerializeToString,
            node__conn__pb2.TextMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
