# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_conn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnode_conn.proto\"\x1e\n\x0bTextMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2M\n\x16LedManipulationService\x12\x33\n\x13StartLedPerformance\x12\x0c.TextMessage\x1a\x0c.TextMessage\"\x00\x62\x06proto3')



_TEXTMESSAGE = DESCRIPTOR.message_types_by_name['TextMessage']
TextMessage = _reflection.GeneratedProtocolMessageType('TextMessage', (_message.Message,), {
  'DESCRIPTOR' : _TEXTMESSAGE,
  '__module__' : 'node_conn_pb2'
  # @@protoc_insertion_point(class_scope:TextMessage)
  })
_sym_db.RegisterMessage(TextMessage)

_LEDMANIPULATIONSERVICE = DESCRIPTOR.services_by_name['LedManipulationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTMESSAGE._serialized_start=19
  _TEXTMESSAGE._serialized_end=49
  _LEDMANIPULATIONSERVICE._serialized_start=51
  _LEDMANIPULATIONSERVICE._serialized_end=128
# @@protoc_insertion_point(module_scope)
